a=int(input("Enter First Number : "))
b=int(input("Enter Second Number : "))
c=int(input("Enter Third Number : "))
print("Arithematic operator  ; ")
print("Add : ",a+b)
print("Sub : ",a-b)
print("Mul : ",a*b)
print("Div : ",a/b)
print("Mod : ",a%b)
print("Exp : ",a**b)
print("Floor Div : ",a//b)
print("Arithematic Operator is Finished-----")
print("Assignment Operator : ")
print("Assign : ",c)
c+=5
print("Add : ",c)
c-=2
print("Sub : ",c)
c*=2
print("Mul : ",c)
c/=5
print("Div : ",c)
c//=7
print("Floor Div : ",c)
c**=6
print("Exp : ",c)
c%=3
print("Mod : ",c)
print("Assignment Operator is finished---")
print("Comparison operator : ")
print(a==b)
print(a!=b)
print(a>b)
print(a<b)
print(a>=b)
print(a<=b)
print("Comparison Operator is Finished ----")
print("Logical Operator : ")
print(a>0 and a<100)
print(a>0 or a>5)
print(not(a>0 and a<100))
print("logical Operator is finished ----")
print("Identity Operator : ")
x=["string","hi"]
y=["string","hi"]
z=x
print(z)
print(x is y)
print(x is z)
print(id(x))
print(id(y))
print(id(z))
print("Identity Operator finished ----")
print("Membership Operator : ")
print("string" in x)
print("hello" not in x)
print("Membership Operator finished ----")
print("Bitwise Operator : ")
print(6 & 3)
print(6 | 3)
print(6 ^ 3)
print(5 ~ 5)
print(6 << 8)
print(2 >> 3)
print("Bitwise Operatoe finished---")
